apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /blue
        backend:
          serviceName: nginx-blue-svc
          servicePort: 80
      - path: /green
        backend:
          serviceName: nginx-green-svc
          servicePort: 80
