apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-serect-file-deployment
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: hello-secret-file
  template:
    metadata:
      name: hello-secret-file
      labels:
        app: hello-secret-file
    spec:
      containers:
      - name: hello-secret-file
        image: (account-id).dkr.ecr.ap-northeast-2.amazonaws.com/hello-secret-file:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: db-password
            mountPath: "/tmp/db-password"
            readOnly: true
      volumes:
      - name: db-password
        secret:
          secretName: db-password
          defaultMode: 0600

